#!/usr/bin/env perl

use warnings;
use strict;

sub pkg{
	my $system = `uname`;
	chomp $system;
	my $pkg;
	$pkg = "pkg" if ($system eq "FreeBSD");
	
	die "Can't find package" if ($pkg eq "");
	
	return $pkg;
}

my $pkg = pkg();
my $command = join ' ', @ARGV;
system("$pkg $command");
